name: TF_LOG=DEBUG check
on:
  issues:
    types: [opened]

jobs:
  tf-log-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - run: make tools
      - run: go run cmd/tf-log-check/main.go ${{ github.event.issue.number }}
        working-directory: ./tools
        env:
          GITHUB_OWNER: cloudflare
          GITHUB_REPO: terraform-provider-cloudflare
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
